# Generated by Django 3.2.3 on 2022-11-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_auto_20221114_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolGenerado',
        ),
        migrations.DeleteModel(
            name='RolPagos',
        ),
    ]
